playbook:
  actions:
    - db.create_engine:
        args:
          url: sqlite:///avocado.db
        result: $engine
    - each:
        args: $news
        actions:
          - sha256:
              args: $_.link
              result: $id
          - dict.set: [$_, id, $id]
          - db.select:
              args:
                engine: $engine
                sql: "SELECT id FROM news WHERE id='{$id}'"
              result: $exists
          - when:
              args: {"eq": [$exists, null]}
              actions:
                - time.now:
                    args:
                      format: "%Y-%m-%d %H:%M:%S"
                    result: $created_at
                - dict.set: [$_, created_at, $created_at]
                - setvar: [title, $_.title]
                - playbook:
                    args: ./news_category.yaml
                    result: $cate
                - when:
                    args: {"ne": [$cate, null]}
                    actions:
                      - log: $cate
                      - dict.set: [$_, title_zh, $cate.title_zh]
                      - dict.set: [$_, classify, $cate.classify]
                      - dict.set: [$_, sentiment, $cate.sentiment]
                      - db.exec:
                          args:
                            engine: $engine
                            sql: |
                              INSERT INTO news (id, title, link, src, pub_date, created_at, title_zh, classify, sentiment)
                              VALUES
                              (:id, :title, :link, :source, :date, :created_at, :title_zh, :classify, :sentiment)
                            values: $_
