playbook:
  actions:
    - llm.session:
        args:
          provider: openai
          llm_args:
            api_key: sk-xxx
            base_url: http://100.64.0.8:8888/v1/
            model: Qwen-14B-Chat-Int4
            #model_path: /Volumes/Workspaces/models/Qwen-1_8B-Chat/ggml-model-q4_0.gguf
            #chat_format: qwen-fn
            #model_path: /Volumes/Workspaces/models/chatglm3-6b/chatglm3-6b-ggml.bin
        result: $session
    - llm.chat:
        args:
          session: $session
          prompt: |
            You are a professional news analyst, and your task is to classify, \
            perform sentiment analysis, and translate news headlines. \
            The output should be in the following Legal JSON format, without other explanations or comments:

            {{
              "title_zh": "Simplified Chinese Title",
              "sentiment": "neutral, positive, negative",
              "classify": "politics, entertainment, technology, finance"
            }}

            Example 1:
            ```
            Title: McDonald's earnings: Sales are still growing, but not as much as Wall Street expected
            JSON Result:
            {{
              "title_zh": "麦当劳的销售额仍在增长，但没有华尔街预期的那么大",
              "sentiment": "negative",
              "classify": "business"
            }}
            ```

            Example 2:
            ```
            Title: Zelenskyy confirms he's thinking of dismissing Ukraine's military chief
            JSON Result:
            {{
              "title_zh": "泽伦斯基确认他正在考虑解雇乌克兰的武装部队总司",
              "sentiment": "neutral",
              "classify": "politics"
            }}
            ```

            Example 3:
            ```
            Title: Fed expects to make three rate cuts this year, says Jay Powell
            JSON Result:
            {{
              "title_zh": "美联储预计今年将降息三次，杰伊·鲍威尔说",
              "sentiment": "positive",
              "classify": "finance"
            }}
            ```

            Please analyze this news title:
            Title: {$title}
            JSON Result:
          #top_k: 2
          #repeat_penalty: 1.2
          #max_tokens: 500
          temperature: 0
          expect_json: 3
        result: $result
