# python -m iauto ./playbooks/browser.yaml --kwargs url=https://bing.com
playbook:
  spec:
    description: Open browser and goto the URL specified.
    arguments:
      - name: url,
        type: string,
        description: HTTP URL,
        required: false
  actions:
    - browser.open:
        args:
          exec: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
          headless: false
        result: $browser
    - browser.goto:
        args:
          browser: $browser
          url: $url
        result: $page
    - browser.eval:
        args:
          page: $page
          javascript: new Date()
        result: $now
    - log: $now
    - time.wait: 2
    - browser.close: $browser
