playbook:
  description: Chat to QWen
  actions:
    - llm.session:
        args:
          provider: llama
          llm_args:
            model_path: /Volumes/Workspaces/models/Qwen-1_8B-Chat/ggml-model-q4_0.gguf
            chat_format: qwen-fn
        result: $session
    - repeat:
        actions:
          - shell.prompt:
              args: "Human: "
              result: $prompt
          - llm.chat:
              args:
                session: $session
                prompt: $prompt
                top_k: 2
                repeat_penalty: 1.2
                max_tokens: 500
              result: $message
          - shell.print:
              args:
                message: "AI: {$message}"
                color: green
