playbook:
  description: Chat to QWen
  actions:
    - llm.session:
        args:
          provider: llama
          llm_args:
            model_path: /Volumes/Workspaces/models/Qwen-1_8B/qwen1_8-ggml-q4_0.bin
            chat_format: qwen
            #model_path: /Volumes/Workspaces/models/chinese-alpaca-2-7b-hf/ggml-model-q4_0.gguf
        result: $session
    - repeat:
        actions:
          - shell.prompt:
              args: "Human: "
              result: $prompt
          - llm.chat:
              args:
                session: $session
                prompt: $prompt
              result: $message
          - shell.print: "AI: {$message}"
