playbook:
  description: Create a LLM chat session
  actions:
    - llm.session:
        args:
          provider: $llm_provider
          llm_args: $llm_args
          tools:
            - shell.cmd
        actions:
          - playbook:
              args:
                - ./bing.yaml
                - ./fetch_links_from_url.yaml
                - ./get_readability_text_from_url.yaml
        result: $session
