playbook:
  description: Chat to ChatGLM with Function callings
  actions:
    - llm.session:
        args:
          provider: chatglm
          llm_args:
            model_path: /Volumes/Workspaces/models/chatglm3-6b/chatglm3-6b-ggml.bin
        actions:
          - playbook:
              args:
                - ./bing.yaml
                - ./google_news.yaml
                - ./get_readability_text_from_url.yaml
        result: $session
    - repeat:
        actions:
          - shell.prompt:
              args: "Human: "
              result: $prompt
          - llm.chat:
              args:
                session: $session
                prompt: "{$prompt}"
              result: $message
          - shell.print: "AI: {$message}"
